# Dockerfile to create containered Python 2 interpretor.
# Useful for OS without explicit Python 2 support, etc. MacOs arm64.
FROM python:2.7
WORKDIR /usr/bin/python2
ENV PYTHONPATH=/usr/bin/python2

# $ docker build . --rm
